# -*- coding: utf-8 -*-
"""SHL Assessment Recommendation Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqxUqU4qjklbbJ5Z59XtGiFg3ISlZo13
"""

"""
SHL Assessment Recommendation Engine
A content-based filtering system using TF-IDF and cosine similarity
to recommend assessments based on job role and required skills.
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')

# Create the SHL Assessment Dataset
def create_assessment_dataset():
    """Create a comprehensive dataset of SHL assessment products"""

    data = {
        'product_id': ['ASM001', 'ASM002', 'ASM003', 'ASM004', 'ASM005',
                       'ASM006', 'ASM007', 'ASM008', 'ASM009', 'ASM010',
                       'ASM011', 'ASM012', 'ASM013', 'ASM014', 'ASM015'],

        'product_name': [
            'Verify G+', 'OPQ32', 'Python Coding Challenge',
            'Situational Judgement Test', 'Numerical Reasoning',
            'Leadership Potential Assessment', 'Verbal Reasoning Test',
            'Sales Aptitude Battery', 'Java Technical Assessment',
            'Emotional Intelligence Inventory', 'Mechanical Reasoning Test',
            'Customer Service Excellence', 'SQL Database Assessment',
            'Abstract Reasoning Test', 'Managerial Competency Profile'
        ],

        'assessment_type': [
            'Cognitive', 'Personality', 'Technical', 'Behavioral', 'Cognitive',
            'Leadership', 'Cognitive', 'Behavioral', 'Technical', 'Personality',
            'Cognitive', 'Behavioral', 'Technical', 'Cognitive', 'Leadership'
        ],

        'suitable_job_roles': [
            'Software Engineer, Data Analyst, Business Analyst, Financial Analyst',
            'Sales Manager, HR Executive, Marketing Manager, Customer Success Manager',
            'Software Engineer, Data Scientist, Backend Developer, DevOps Engineer',
            'HR Executive, Team Leader, Project Manager, Customer Service Manager',
            'Financial Analyst, Accountant, Business Analyst, Data Analyst',
            'Senior Manager, Director, Team Leader, Department Head',
            'Content Writer, Marketing Manager, Legal Advisor, HR Executive',
            'Sales Manager, Business Development Executive, Account Manager, Sales Representative',
            'Software Engineer, Java Developer, System Architect, Backend Developer',
            'HR Executive, Counselor, Team Leader, Customer Success Manager',
            'Mechanical Engineer, Manufacturing Engineer, Quality Control Inspector, Technician',
            'Customer Service Manager, Support Specialist, Call Center Agent, Client Relations Manager',
            'Data Analyst, Database Administrator, Backend Developer, Data Engineer',
            'Software Engineer, Research Analyst, Strategy Consultant, Product Designer',
            'Project Manager, Operations Manager, Team Leader, Department Manager'
        ],

        'difficulty_level': [
            'Advanced', 'Intermediate', 'Advanced', 'Intermediate', 'Intermediate',
            'Advanced', 'Intermediate', 'Intermediate', 'Advanced', 'Beginner',
            'Intermediate', 'Beginner', 'Intermediate', 'Advanced', 'Advanced'
        ],

        'skills_measured': [
            'Problem-solving, logical reasoning, numerical analysis, critical thinking',
            'Emotional intelligence, teamwork, leadership style, communication, adaptability',
            'Python programming, algorithms, data structures, debugging, code optimization',
            'Decision-making, interpersonal skills, conflict resolution, ethical judgment',
            'Data interpretation, statistical analysis, numerical computation, pattern recognition',
            'Strategic thinking, vision, influence, change management, team motivation',
            'Reading comprehension, logical inference, verbal analysis, communication clarity',
            'Persuasion, negotiation, resilience, customer engagement, goal orientation',
            'Java programming, object-oriented design, multithreading, exception handling, JVM concepts',
            'Self-awareness, empathy, emotional regulation, social skills, relationship management',
            'Mechanical concepts, spatial reasoning, physics principles, tool knowledge',
            'Active listening, problem-solving, patience, communication, service orientation',
            'SQL queries, database design, data manipulation, optimization, joins and aggregations',
            'Pattern recognition, logical thinking, abstract problem-solving, inductive reasoning',
            'Planning and organizing, delegation, performance management, resource allocation, accountability'
        ]
    }

    return pd.DataFrame(data)


class AssessmentRecommendationEngine:
    """
    Content-based recommendation engine using TF-IDF vectorization
    and cosine similarity for assessment matching.
    """

    def __init__(self, assessment_df):
        self.df = assessment_df.copy()
        self.vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))
        self._prepare_features()

    def _prepare_features(self):
        """Combine relevant features into a single text corpus for each assessment"""
        self.df['combined_features'] = (
            self.df['assessment_type'] + ' ' +
            self.df['suitable_job_roles'] + ' ' +
            self.df['skills_measured'] + ' ' +
            self.df['difficulty_level']
        )

        # Create TF-IDF matrix
        self.tfidf_matrix = self.vectorizer.fit_transform(self.df['combined_features'])

    def recommend_assessments(self, job_role, required_skills, top_n=5):
        """
        Recommend assessments based on job role and required skills

        Parameters:
        -----------
        job_role : str
            Target job role (e.g., "Software Engineer")
        required_skills : str
            Comma-separated skills required (e.g., "Python, problem-solving, algorithms")
        top_n : int
            Number of recommendations to return (default: 5)

        Returns:
        --------
        DataFrame with recommended assessments and similarity scores
        """

        # Create user query by combining job role and skills
        user_query = f"{job_role} {required_skills}"

        # Transform user query using the same vectorizer
        query_vector = self.vectorizer.transform([user_query])

        # Calculate cosine similarity between query and all assessments
        similarity_scores = cosine_similarity(query_vector, self.tfidf_matrix).flatten()

        # Add similarity scores to dataframe
        recommendations = self.df.copy()
        recommendations['similarity_score'] = similarity_scores

        # Sort by similarity score and get top N
        recommendations = recommendations.sort_values(
            'similarity_score',
            ascending=False
        ).head(top_n)

        # Format output
        output = recommendations[[
            'product_id', 'product_name', 'assessment_type',
            'difficulty_level', 'similarity_score'
        ]].copy()

        output['similarity_score'] = output['similarity_score'].round(3)
        output['match_percentage'] = (output['similarity_score'] * 100).round(1)

        return output

    def display_recommendations(self, job_role, required_skills, top_n=5):
        """
        Display recommendations in a formatted way with detailed information
        """
        print("="*80)
        print(f"ASSESSMENT RECOMMENDATIONS FOR: {job_role.upper()}")
        print("="*80)
        print(f"Required Skills: {required_skills}")
        print("-"*80)

        recommendations = self.recommend_assessments(job_role, required_skills, top_n)

        for idx, row in recommendations.iterrows():
            assessment_details = self.df[self.df['product_id'] == row['product_id']].iloc[0]

            print(f"\n Recommendation #{recommendations.index.get_loc(idx) + 1}")
            print(f"   Product ID: {row['product_id']}")
            print(f"   Name: {row['product_name']}")
            print(f"   Type: {row['assessment_type']}")
            print(f"   Difficulty: {row['difficulty_level']}")
            print(f"   Match Score: {row['match_percentage']}%")
            print(f"   Skills Measured: {assessment_details['skills_measured']}")
            print(f"   Suitable Roles: {assessment_details['suitable_job_roles']}")

        print("\n" + "="*80 + "\n")


# Main Execution
if __name__ == "__main__":

    print("Initializing SHL Assessment Recommendation Engine...")
    print()

    # Create dataset
    assessment_df = create_assessment_dataset()

    # Initialize recommendation engine
    engine = AssessmentRecommendationEngine(assessment_df)

    print(" Engine initialized successfully!")
    print(f" Loaded {len(assessment_df)} assessment products")
    print()

    # Example 1: Software Engineer
    engine.display_recommendations(
        job_role="Software Engineer",
        required_skills="Python, algorithms, problem-solving, data structures, debugging",
        top_n=5
    )

    # Example 2: Sales Manager
    engine.display_recommendations(
        job_role="Sales Manager",
        required_skills="persuasion, negotiation, customer engagement, leadership, communication",
        top_n=5
    )

    # Example 3: HR Executive
    engine.display_recommendations(
        job_role="HR Executive",
        required_skills="emotional intelligence, communication, decision-making, interpersonal skills",
        top_n=5
    )

    # Show dataset summary
    print("\n" + "="*80)
    print("DATASET SUMMARY")
    print("="*80)
    print(f"\nTotal Assessments: {len(assessment_df)}")
    print(f"\nAssessment Types:")
    print(assessment_df['assessment_type'].value_counts())
    print(f"\nDifficulty Distribution:")
    print(assessment_df['difficulty_level'].value_counts())